site_name: SIG Multicluster
repo_url: https://github.com/lauralorenz/sig-multicluster-site-proposal
repo_name: lauralorenz/sig-multicluster-site-proposal
site_dir: site-src
docs_dir: site-src
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/k8s-favicon.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
edit_uri: edit/main/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      include_dir: examples
      j2_line_comment_prefix: "#$"
  - redirects:
      redirect_maps:
        'guides/getting-started.md': 'guides/index.md'
        'contributing/community.md': 'contributing/index.md'
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
nav:
  - Overview:
    - Introduction: index.md
    - Concepts:
        Multicluster API Overview: concepts/multicluster-api-overview.md
        About API Overview: concepts/about-api-overview.md
        Work API Overview: concepts/work-api-overview.md
        Conformance: concepts/conformance.md
        Security Model: concepts/security-model.md
        Implementation Guidelines: concepts/guidelines.md
        Versioning: concepts/versioning.md
    - Implementations: implementations.md
    - FAQ: faq.md
  - Guides:
    - Getting started: guides/index.md
  - Reference:
    - API Types:
        ServiceExport: api-types/service-export.md
        ServiceImport: api-types/service-import.md
    - API specification: references/spec.md
  - Contributing:
    - How to Get Involved: contributing/index.md
    - Developer Guide: contributing/devguide.md
  - Blog:
    - Index: blog/index.md